[unstable]
build-std = ["core", "compiler_builtins", "alloc"]

[build]
target = "x86_64-enchanted-kernel.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner" # TODO: Change when new bootloader is implemented!